### ISSUE TITLE
なぜかうまくIssue上げられません

### ISSUE THREAD

**Issue by MasudaNaika** [dolphin-dev/OpenDolphin#9]
修正お願いします
ClaimResource.java
line 207
{"SHIN_GENERAL_ORDER", "\\\\d"}
→{"SHIN_GENERAL_ORDER", "\\d{3}"}

AbstractStampEditor.java
line 603
else if (test.equals(clb.getString("OTHER")))
→else if (test.equals(clb.getString("SLOT_OTHER")))

**Comment by dolphin-dev** [comment]
ご連絡をありがとうございます。
両方修正いたします。
